spring:
  application:
    name: eplan-discovery
server:
  port: 9020
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
